version: '3.5'
services:
  crawling:
    build: crawling
    image: "alai04/crawling"
    volumes:
      - ./srcmap:/opt/crawling/map
    command: ["./crawling", "-d", "/opt/crawling/map", "-w", "10", "-l", "11"] 
    restart: always

  filesrv:
    build: filesrv
    image: "alai04/filesrv"
    ports: 
      - "8080:8080"
    volumes:
      - ./dstmap:/opt/filesrv/map
    command: ["./filesrv", "-d", "/opt/filesrv/map/"] 
    restart: always

  adjust:
    build: adjust
    image: "alai04/adjust"
    ports: 
      - "9101:8080"
    volumes:
      - ./srcmap:/opt/adjust/srcmap
      - ./dstmap:/opt/adjust/dstmap
    command: ["./adjust", "-sd", "/opt/adjust/srcmap", "-dd", "/opt/adjust/dstmap"] 
    restart: always