version: '3.5'
services:
  crawling:
    build: crawling
    image: "alai04/crawling"
    environment:
      - CRAWLING_WORKERS=10
      - CRAWLING_MAXLEVEL=11
      - MAP_DIR=/opt/crawling/map/
    volumes:
      - ./map:/opt/crawling/map
    command: [./crawling] 
    restart: always

  filesrv:
    build: filesrv
    image: "alai04/filesrv"
    environment:
      - MAP_DIR=/opt/filesrv/map/
    ports: 
      - "8080:8080"
    volumes:
      - ./map:/opt/filesrv/map
    command: [./filesrv] 
    restart: always
