version: '3.5'
services:
  crawling:
    build: crawling
    image: "alai04/crawling"
    volumes:
      - ./map:/opt/crawling/map
    command: ["./crawling", "-d", "/opt/crawling/map", "-w", "10", "-l", "11"] 
    restart: always

  filesrv:
    build: filesrv
    image: "alai04/filesrv"
    environment:
      - MAP_DIR=/opt/filesrv/map/
    ports: 
      - "8080:8080"
    volumes:
      - ./map:/opt/filesrv/map
    command: [./filesrv] 
    restart: always
